export const profile = {
  name: 'Carld Similien',
  tagline: 'IA · Imagerie médicale · MLOps',
  location: 'Stains, Île-de-France',
  // email encodé en base64 : évite que le texte brut soit dans le HTML statique
  // (anti-scraping bots à spam). Décodé côté client uniquement, voir app/contact/page.jsx
  emailEncoded: 'Y2FybGQuc2ltaWxpZW5AZ21haWwuY29t',
  github: 'https://github.com/sheene123',
  linkedin: 'https://www.linkedin.com/in/carld-similien-176439297/',
  about:
    "Je suis en Master 1 Optique, Image, Vision, Multimédia à l'UPEC, parcours Signaux et Images en Médecine, après un BUT Informatique dont la dernière année s'est faite en alternance chez Framatome. J'y ai automatisé le traitement des données d'une direction métier et déployé des applications sur Kubernetes. Aujourd'hui, je construis des modèles d'IA pour l'imagerie médicale et toute la chaîne qui les entoure : données versionnées, évaluation honnête face aux experts, déploiement continu et démos utilisables dans le navigateur. Je recherche une alternance de 12 mois en intelligence artificielle, idéalement autour de l'image médicale.",
};

export const skills = [
  { icon: '🩻', name: 'Imagerie médicale', detail: "Fond d'œil (segmentation, biomarqueurs, dépistage), tomographie d'impédance électrique" },
  { icon: '🧠', name: 'Deep learning', detail: 'PyTorch, U-Net, EfficientNet, transfert d\'apprentissage, TensorFlow et Keras' },
  { icon: '🔁', name: 'MLOps', detail: 'DVC, MLflow, registre de modèles, champion / challenger, export ONNX, quality gates' },
  { icon: '📐', name: 'Signal et image', detail: 'Filtrage, CLAHE, Frangi, graphes de pixels (Dijkstra, A*), éléments finis' },
  { icon: '📏', name: 'Évaluation et statistiques', detail: 'Validation croisée groupée, bootstrap, calibrage, AUROC, tests appariés' },
  { icon: '💬', name: 'IA générative et RAG', detail: 'LangChain, FAISS, embeddings, reranking, LLM locaux et API' },
  { icon: '🐍', name: 'Python scientifique', detail: 'NumPy, SciPy, pandas, scikit-learn, scikit-image, FastAPI' },
  { icon: '🚀', name: 'CI/CD', detail: 'GitHub Actions, déploiement continu, tests automatisés, releases' },
  { icon: '🐳', name: 'Cloud et conteneurs', detail: 'Docker, Kubernetes (Azure AKS), Terraform, GCP, Prometheus et Grafana' },
  { icon: '🗄️', name: 'Données', detail: 'SQL, PostgreSQL, Neo4j, Dataverse, Power BI, Power Automate' },
  { icon: '💻', name: 'Web', detail: 'Next.js, React, ONNX Runtime Web, Pyodide, FastAPI' },
  { icon: '📱', name: 'Mobile', detail: 'Kotlin, Android, React Native et Expo' },
];

export const experiences = [
  {
    id: 'framatome',
    type: 'Alternance',
    role: 'Développeur PowerApps/JavaScript & Automatisation',
    org: 'Framatome',
    place: 'Paris La Défense',
    period: 'sept. 2025 - sept. 2026',
    missions: [
      "Déploiement et administration de clusters Kubernetes sur Azure (AKS) : exposition des services, gestion du cycle de vie des déploiements, optimisation de la consommation et des coûts (FinOps).",
      "Provisionnement de l'infrastructure avec Terraform, état distant sur GitLab, pipelines CI/CD avec contrôles automatisés.",
      "Mise en place d'une chaîne d'observabilité Prometheus / Grafana : instrumentation FastAPI, métriques de latence, de débit et d'erreurs, tableaux de bord PromQL.",
      "Développement d'une interface web Next.js / Node.js / FastAPI interrogeant Dataverse, comme alternative à PowerApps.",
      "Évolution et optimisation d'une application métier sous Power Apps.",
      "Automatisation de la collecte et du traitement des données (Python, Power Automate) pour alimenter les tableaux de bord Power BI. Le temps de traitement manuel a baissé de 45 %.",
      "Gestion des permissions Azure AD / IAM sur un site classé OIV, avec les exigences de sécurité renforcées que ça implique.",
      "Exploitation dans un réseau d'entreprise contraint : accès applicatifs derrière le proxy, diagnostic d'incidents de connectivité (résolution DNS, certificats TLS, filtrage des flux sortants).",
      "Analyse de données et création de KPI, documentation technique et publication des versions.",
    ],
    stack: ['Kubernetes', 'Azure AKS', 'Terraform', 'Docker', 'Prometheus', 'Grafana', 'CI/CD', 'FinOps', 'Azure AD / IAM', 'Next.js', 'FastAPI', 'Python', 'Power Apps', 'Power Automate', 'Power BI'],
  },
  {
    id: 'edf',
    type: 'Stage',
    role: "Développement d'une application d'automatisation",
    org: 'EDF R&D',
    place: 'Lab les Renardières',
    period: 'jan. 2025 - avr. 2025',
    missions: [
      "Développement d'un outil VBA automatisant la rédaction des rapports d'essais.",
      "Développement et optimisation d'une base de données Access.",
      "Recueil des besoins auprès des ingénieurs, techniciens et responsables de laboratoire.",
      "Intégration de code SQL et consommation d'une API REST interne.",
      "Tests puis déploiement de l'application sur les postes du laboratoire d'essais.",
      "Formation de 30 utilisateurs sur l'application livrée.",
    ],
    stack: ['VBA', 'Access', 'SQL', 'API REST'],
  },
];

export const education = [
  { degree: 'Master Optique, Image, Vision, Multimédia (OIVM), parcours Signaux et Images en Médecine', school: 'Université Paris-Est Créteil (UPEC), Vitry-sur-Seine', period: 'depuis sept. 2026' },
  { degree: 'BUT Informatique', school: 'Université Sorbonne Paris Nord, Villetaneuse', period: '2023 - 2026' },
  { degree: 'Baccalauréat STI2D', school: 'Lycée Simone de Beauvoir, Garges-lès-Gonesse', period: '2023' },
];

export const projects = [
  {
    slug: 'retina-vessel-tracing',
    title: 'Vaisseaux rétiniens et maladies de l\'œil',
    year: '2026',
    category: 'Imagerie',
    github: 'https://github.com/sheene123/retina-vessel-tracing',
    demo: 'https://huggingface.co/spaces/sheenee261/retina-vessel-tracing',
    short: "Tracé des vaisseaux du fond d'œil, mesures vasculaires et détection de six maladies avec des pourcentages calibrés, dans le navigateur.",
    context:
      "Projet personnel de recherche sur les photos du fond d'œil. On place deux points sur une rétinographie et le vaisseau qui les relie est tracé par plus court chemin sur le graphe des pixels (Dijkstra, A*), à partir d'une carte qui fait ressortir les vaisseaux (filtre de Frangi). Un U-Net segmente tout le réseau (Dice 0,82, AUC 0,98 sur le test DRIVE), puis des biomarqueurs sont mesurés : densité, calibre, tortuosité, bifurcations, dimension fractale. La question de fond est l'évaluation face à une vérité terrain experte. Une étude sur 380 segmentations montre que le Dice prédit bien le calibre, mais pas la tortuosité ni les bifurcations, et que deux experts ne s'accordent eux-mêmes qu'en partie. Un second réseau (EfficientNet) repère six maladies (rétinopathie diabétique, glaucome, cataracte, DMLA, rétinopathie hypertensive, myopie forte), avec des AUROC de 0,82 à 0,99 en validation croisée par patient et des pourcentages calibrés. Tout s'exécute dans le navigateur : aucune image n'est envoyée à un serveur.",
    missions: [
      "Tracer un vaisseau entre deux points par plus court chemin (Dijkstra, A*) sur un coût issu du filtre de Frangi, après prétraitement (CLAHE, débruitage).",
      "Entraîner un U-Net de segmentation sur DRIVE sur GPU et l'exporter en ONNX.",
      "Mesurer des biomarqueurs vasculaires et étudier leur fiabilité face à deux experts (corrélations, bootstrap, tests de Wilcoxon avec correction de Holm).",
      "Détecter six maladies sur ODIR-5K avec une validation croisée groupée par patient, un calibrage de Platt et des intervalles de confiance par bootstrap.",
      "Étendre l'entraînement à quatre bases publiques (ODIR-5K, RFMiD, SMDG-19, sjchoi86) avec dédoublonnage, et mesurer la généralisation sur un hôpital jamais vu (JSIEC-1000).",
      "Mettre en place le MLOps : registre de modèles versionné sur Hugging Face, comparaison champion / challenger, validation indépendante en CI, image Docker sur GHCR, releases.",
      "Construire la démo web (Pyodide, ONNX Runtime Web) : recadrage automatique de l'œil, comparaison à la vérité terrain, pourcentages lisibles.",
    ],
    stack: ['PyTorch', 'U-Net', 'EfficientNet', 'ONNX', 'scikit-image', 'Dijkstra / A*', 'FastAPI', 'Docker', 'GitHub Actions', 'Hugging Face', 'Pyodide'],
  },
  {
    slug: 'pulmoeit',
    title: 'PulmoEIT : imagerie pulmonaire portable',
    year: '2026',
    category: 'Imagerie',
    github: 'https://github.com/sheene123/pulmoeit',
    demo: 'https://huggingface.co/spaces/sheenee261/pulmoeit',
    short: "Reconstruction d'images de ventilation pulmonaire par deep learning pour des ceintures EIT portables, avec une chaîne MLOps complète.",
    context:
      "La tomographie d'impédance électrique (EIT) suit la ventilation des poumons au lit du patient, sans radiation, avec une simple ceinture de 16 électrodes. Mais le problème inverse est très mal posé et les images des algorithmes linéaires sont floues. J'ai écrit un simulateur par éléments finis (modèle d'électrodes complet) et des fantômes pathologiques (SDRA, pneumothorax, épanchement, intubation sélective), puis entraîné un réseau qui corrige la reconstruction NOSER. En simulation, la corrélation avec la vérité passe de 0,85 à 0,99, et de 0,77 à 0,94 quand le thorax et la ceinture changent. Un contrôle qualité détecte une électrode décollée dans 100 % des cas pour 0,6 % de fausses alarmes. Résultats obtenus en simulation : la validation sur données réelles reste à faire.",
    missions: [
      "Écrire un simulateur FEM validé (réciprocité, jacobien par méthode adjointe, différences finies) et une domain randomisation du thorax et de la ceinture.",
      "Comparer la reconstruction linéaire NOSER à un PostUNet et à un inverse entièrement appris, avec des indices cliniques (GI, centre de ventilation).",
      "Construire le pipeline DVC et le suivi MLflow, avec des quality gates bloquantes et un export ONNX vérifié par test de parité.",
      "Surveiller les mesures en production : score de plausibilité, localisation de l'électrode fautive, test de dérive de Kolmogorov-Smirnov.",
      "Mettre en place le déploiement continu : réentraînement en CI à chaque version, champion / challenger, registre de modèles, image Docker, démo et release.",
    ],
    stack: ['PyTorch', 'NumPy / SciPy', 'Éléments finis', 'DVC', 'MLflow', 'ONNX', 'FastAPI', 'Docker', 'GitHub Actions', 'Hugging Face'],
  },
  {
    slug: 'voyage-assistant',
    title: 'Voyage Assistant, chatbot RAG',
    year: '2026',
    category: 'IA',
    github: 'https://github.com/optmlako2004/chatbot',
    demo: 'https://optimalako-voyage-assistant.hf.space',
    short: "Chatbot d'agence de voyage avec pipeline RAG, authentification, réservation de billets et déploiement Docker sur Hugging Face Spaces.",
    context:
      "Projet universitaire (SAE BUT3) : concevoir un assistant virtuel pour une agence de voyage. Le chatbot répond aux questions sur les trajets grâce à un pipeline RAG qui interroge un catalogue de plus de 182 000 trajets stocké sur PostgreSQL (Neon en production), avec des embeddings gte-small et un reranker cross-encoder. Backend, frontend et modèles tournent dans un seul conteneur Docker déployé sur Hugging Face Spaces.",
    missions: [
      "Mettre en place le pipeline RAG (LangChain, FAISS, embeddings gte-small et reranker) pour la recherche sémantique sur les trajets et les CGV.",
      "Développer le backend FastAPI avec SQLAlchemy et Pydantic : routes auth, trajets, billets, réclamations, chat, documentation OpenAPI.",
      "Construire le frontend en JavaScript natif (fetch API), servi statiquement par FastAPI.",
      "Migrer la persistance de SQLite vers PostgreSQL (Neon) pour la mise en production.",
      "Conteneuriser avec Docker et déployer sur Hugging Face Spaces via CI/CD.",
      "Gérer l'authentification par sessions et intégrer Google OAuth.",
      "Optimiser le contexte envoyé au modèle (chunking, reranking) pour réduire la consommation de tokens.",
    ],
    stack: ['Python', 'FastAPI', 'LangChain', 'FAISS', 'RAG', 'PostgreSQL', 'Docker', 'Hugging Face Spaces', 'JavaScript'],
  },
  {
    slug: 'appcatalog',
    title: 'AppCatalog : cartographie du SI',
    year: '2026',
    category: 'DevOps',
    github: 'https://github.com/sheene123/AppCatalog',
    short: "Référentiel d'applications modélisé en base graphe Neo4j, avec analyse d'impact des pannes. Architecture trois tiers déployée sur Azure AKS via Terraform et une chaîne CI/CD complète.",
    context:
      "Un référentiel des applications d'un système d'information, où les dépendances entre applications sont modélisées comme un graphe (Neo4j) plutôt qu'un simple tableau. On peut ainsi répondre à « quelles applications tombent si ce service tombe ? » en une requête, en suivant les dépendances en cascade. L'ensemble est une architecture trois tiers (frontend Blazor, API ASP.NET Core, base Neo4j) déployée sur Kubernetes managé Azure (AKS), avec l'infrastructure décrite en Terraform, les secrets gérés par Azure Key Vault, un cloisonnement réseau strict et une chaîne CI/CD qui construit et déploie automatiquement à chaque push.",
    missions: [
      "Modéliser le référentiel en graphe (nœuds Application, relations de dépendance) et l'analyse d'impact transitive en Cypher.",
      "Développer l'API REST en ASP.NET Core 8 et le frontend Blazor, avec une cartographie interactive des dépendances.",
      "Provisionner l'infrastructure Azure (AKS, Container Registry, Key Vault) avec Terraform.",
      "Déployer sur Kubernetes : StatefulSet Neo4j, NetworkPolicies zero-trust, Ingress HTTPS avec certificat Let's Encrypt, secrets montés depuis Key Vault via le CSI Secret Store.",
      "Mettre en place la CI/CD GitHub Actions en OIDC, sans secret stocké : build des images, publication sur ACR, déploiement sur AKS.",
      "Sécuriser de bout en bout : lecture publique, écriture authentifiée, audit des dépendances vulnérables, tests d'intégration contre un vrai Neo4j.",
    ],
    stack: ['Blazor', 'ASP.NET Core', 'C#', 'Neo4j', 'Azure AKS', 'Terraform', 'Kubernetes', 'Docker', 'Key Vault', 'CI/CD', 'HTTPS'],
  },
  {
    slug: 'cloud-kubernetes-finops',
    title: 'Migration cloud-native : de PowerApps à Kubernetes',
    year: '2025 - 2026',
    category: 'DevOps',
    short: "Migration d'une appli interne PowerApps vers une stack Next.js / FastAPI, conteneurisée et déployée sur Azure AKS avec supervision Prometheus.",
    context:
      "Une application métier interne tournait sous PowerApps, et l'idée était de voir concrètement ce que donnerait sa migration vers une stack plus classique. J'ai construit une démonstration complète : une application Next.js / Node.js / FastAPI qui reprend les mêmes usages, conteneurisée avec Docker et déployée sur un cluster Kubernetes managé Azure (AKS). Le cluster est provisionné avec Terraform et supervisé avec Prometheus et Grafana. Elle sert maintenant de modèle pour d'autres migrations du même type.",
    missions: [
      "Reproduire les fonctionnalités de l'application PowerApps existante en Next.js / Node.js / FastAPI, avec accès aux données Dataverse.",
      "Conteneuriser l'application avec Docker et la déployer sur un cluster Kubernetes managé Azure (AKS).",
      "Provisionner l'infrastructure avec Terraform, état distant sur GitLab.",
      "Instrumenter le backend FastAPI et construire les tableaux de bord PromQL (latence, débit, taux d'erreur).",
      "Mettre en place la chaîne CI/CD jusqu'à la mise en production.",
      "Optimiser la consommation et les coûts du cluster (FinOps).",
      "Documenter le tout pour en faire un modèle réutilisable.",
    ],
    stack: ['Next.js', 'FastAPI', 'Docker', 'Kubernetes', 'Azure AKS', 'Terraform', 'Prometheus', 'Grafana', 'CI/CD', 'FinOps'],
  },
  {
    slug: 'trading-cloud',
    title: 'Automatisation cloud sur GCP',
    year: '2024',
    category: 'Cloud',
    short: "Scripts Python d'achats d'actions via l'API Interactive Brokers, exécutés par systemd sur une instance GCE durcie.",
    context:
      "Projet personnel : automatiser une stratégie d'achat d'actions, depuis l'appel d'API jusqu'à l'exécution planifiée dans le cloud. J'ai déployé et administré une instance Linux sur Google Compute Engine, configuré les règles de pare-feu VPC et durci l'accès SSH (authentification par clés, restriction des adresses sources). Les scripts Python sont déclenchés par des services systemd.",
    missions: [
      "Écrire les scripts Python d'automatisation des ordres d'achat.",
      "Intégrer l'API Interactive Brokers (authentification, requêtes, gestion des réponses).",
      "Déployer et maintenir une instance Linux sur Google Compute Engine.",
      "Configurer les règles de pare-feu VPC et durcir l'accès SSH.",
      "Mettre en place des services systemd pour l'exécution planifiée.",
      "Analyser les journaux et diagnostiquer les coupures de session.",
    ],
    stack: ['Python', 'GCP', 'Compute Engine', 'Linux', 'systemd', 'API REST'],
  },
  {
    slug: 'audit-securite-web',
    title: "Audit de sécurité d'une application web",
    year: '2026',
    category: 'Cyber',
    short: "Audit défensif d'une application React en production : XSS, jeton exposé, dépendances vulnérables, en-têtes de sécurité.",
    context:
      "J'ai audité une application React / Vite en production pour mettre en pratique ce que je travaille en cybersécurité en dehors des cours. J'y ai relevé des vulnérabilités d'injection (XSS), un jeton d'authentification exposé côté client, des dépendances vulnérables et un secret d'API accessible. J'ai aussi analysé les en-têtes HTTP de sécurité (CSP, HSTS). Les constats ont été remontés au propriétaire de l'application sous forme de recommandations classées par criticité.",
    missions: [
      "Reconnaissance et cartographie de la surface d'attaque de l'application.",
      "Identification des points d'injection XSS et de l'exposition du jeton d'authentification.",
      "Revue des dépendances et détection d'un secret d'API exposé dans le bundle.",
      "Analyse des en-têtes HTTP de sécurité (CSP, HSTS) et de la configuration TLS.",
      "Rédaction d'un rapport avec recommandations priorisées par criticité.",
    ],
    stack: ['React', 'OWASP Top 10', 'XSS', 'JWT', 'CSP / HSTS', 'TLS'],
  },
  {
    slug: 'reconnaissance-faciale',
    title: 'Reconnaissance faciale sur mobile',
    year: '2025 - 2026',
    category: 'IA',
    short: 'CNN entraîné from scratch avec TensorFlow, comparé à MobileNet, puis embarqué dans une application Android en Kotlin.',
    context:
      "Projet universitaire de groupe mené sur plusieurs mois : entraîner un modèle de reconnaissance faciale sur le dataset UTKFace, puis l'embarquer dans une application Android utilisable en conditions réelles. On a comparé un CNN développé from scratch au modèle pré-entraîné MobileNet pour voir ce que coûtait la précision en poids et en temps d'inférence sur mobile.",
    missions: [
      'Prétraiter le dataset UTKFace (traitement des images, normalisation).',
      "Développer et entraîner un CNN avec TensorFlow et Keras.",
      'Comparer le modèle from scratch à MobileNet sur la précision et la latence.',
      "Intégrer le modèle retenu dans une application mobile Kotlin.",
    ],
    stack: ['Python', 'TensorFlow', 'Keras', 'CNN', 'Kotlin', 'Android'],
  },
  {
    slug: 'sentiment-chatbot',
    title: 'Sentiment Chatbot',
    year: '2026',
    category: 'IA',
    short: "API Flask servant un RNN TensorFlow d'analyse de sentiment, entraîné sur des critiques de films.",
    context:
      "Projet de S6 : construire un système d'analyse de sentiment et le rendre interrogeable par une API. Le modèle est un empilement d'embeddings et de SimpleRNN, entraîné sur un corpus de critiques de films, sauvegardé puis servi par une API Flask. Une interface Streamlit permet de le tester.",
    missions: [
      'Prétraiter et tokeniser le corpus (pad_sequences, vocabulaire de 10 000 mots).',
      "Concevoir le RNN avec TensorFlow et Keras (Embedding puis SimpleRNN empilés).",
      "Entraîner le modèle, sauvegarder les poids et gérer le rechargement.",
      "Exposer le modèle par une API Flask (endpoint de prédiction JSON).",
      'Construire une interface de test avec Streamlit.',
    ],
    stack: ['Python', 'TensorFlow', 'Keras', 'Flask', 'Streamlit', 'NLP'],
  },
  {
    slug: 'llm-ollama',
    title: 'Agents LLM en local et via API',
    year: '2026',
    category: 'IA',
    short: 'Exécution de LLMs en local avec Ollama et via OpenRouter, intégrés dans des pipelines Python.',
    context:
      "Projet SAE sur l'intégration de grands modèles de langage dans des applications. J'ai fait tourner des modèles open source en local avec Ollama (Llama 3, Mistral, Phi-3) et appelé des modèles distants via l'API OpenRouter, en gérant les prompts et le parsing des réponses JSON.",
    missions: [
      'Installer et exécuter des modèles open source en local avec Ollama.',
      "Intégrer l'API OpenRouter (requêtes REST, authentification, parsing JSON).",
      'Comparer Llama 3, Mistral et Phi-3 sur des cas concrets.',
      'Construire des pipelines de prompts en Python.',
    ],
    stack: ['Python', 'Ollama', 'OpenRouter', 'LLM', 'REST API'],
  },
  {
    slug: 'churchfinder',
    title: 'ChurchFinder',
    year: '2026',
    category: 'Web',
    short: 'Application mobile de recherche de lieux de culte géolocalisés : Expo / React Native, backend FastAPI GraphQL, CockroachDB.',
    context:
      "Projet personnel en cours de développement. L'application mobile est développée avec Expo et React Native, avec une carte react-native-maps et des filtres (confession, style, langue, rayon, ouverture du jour) gérés par un store Zustand. Le backend est une API GraphQL en FastAPI, dockerisée, adossée à une base CockroachDB compatible PostgreSQL qui référence pour l'instant une soixantaine de lieux en France.",
    missions: [
      "Développer l'application mobile avec Expo, React Native et expo-router.",
      "Intégrer la carte et la géolocalisation (react-native-maps, bottom sheet).",
      "Gérer les filtres de recherche et l'état de l'application avec Zustand.",
      "Construire l'API GraphQL en FastAPI et modéliser la base CockroachDB.",
      "Conteneuriser l'environnement de développement avec Docker Compose.",
    ],
    stack: ['React Native', 'Expo', 'FastAPI', 'GraphQL', 'CockroachDB', 'Docker', 'Zustand'],
  },
  {
    slug: 'gestion-stages',
    title: 'Application de gestion de stages',
    year: '2024 - 2025',
    category: 'Web',
    short: 'Site web livré à un client, mené en SCRUM, avec hachage Bcrypt des mots de passe.',
    context:
      "Projet universitaire encadré par un professeur qui jouait le rôle du client : concevoir et livrer une application web de gestion des stages, du recueil des besoins jusqu'à la livraison, en méthode agile SCRUM. Le travail a beaucoup porté sur la modélisation de la base de données et sur la sécurisation des comptes (hachage Bcrypt).",
    missions: [
      'Recueillir les besoins et formaliser le cahier des charges.',
      'Piloter le projet en SCRUM (sprints, backlog, démonstrations client).',
      'Concevoir le site web et le modèle de données.',
      'Sécuriser les mots de passe par hachage Bcrypt.',
    ],
    stack: ['PHP', 'SQL', 'Web', 'SCRUM', 'Bcrypt'],
  },
];
